version: '3'
services:
  php-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mariadb-db
    networks:
      - api-php

  mariadb-db:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - api-php
    volumes:
      - mariadb-data:/var/lib/mysql

  frontend:
    image: wwe-front  
    ports:
      - "5000:80"
    networks:
      - api-php

networks:
  api-php:
    driver: bridge

volumes:
  mariadb-data: